# Generated by Django 5.2.2 on 2025-06-06 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_inicio", models.DateField()),
                ("tasa_anual", models.DecimalField(decimal_places=2, max_digits=5)),
                ("plazo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plazo", models.IntegerField(help_text="Plazo en meses")),
                ("tasa_anual", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "frecuencia_pago",
                    models.CharField(
                        choices=[("mensual", "Mensual"), ("semanal", "Semanal")],
                        default="mensual",
                        max_length=10,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="finanzas.prestamo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncrementoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                (
                    "nuevo_plazo",
                    models.IntegerField(
                        blank=True, help_text="Nuevo plazo en meses", null=True
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incrementos",
                        to="finanzas.prestamo",
                    ),
                ),
            ],
        ),
    ]
