# Generated by Django 5.2.2 on 2025-06-07 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pago",
            old_name="monto_pagado",
            new_name="monto",
        ),
        migrations.AlterField(
            model_name="pago",
            name="fecha_pago",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
